package: anaconda-notebook
user: anaconda-notebook

platform:
  - linux-64
  - osx-64
  - win-64

engine:
  - python=2.7
  - python=3.4

install:
  - conda build conda.recipe
  - conda install anaconda-notebook -c anaconda-notebook --use-local

test:
  - anaconda-notebook --help

script:
  - conda build --no-test ./conda.recipe/

build_targets: conda
