package: anaconda-notebook
user: anaconda-notebook

platform:
  - linux-64
  # - osx-64

engine:
  - python=2.7
  - python=3.4

script:
  - conda build --no-test ./conda.recipe/

build_targets: conda
