package: anaconda-notebook
user: anaconda-notebook

platform:
  - linux-64
  - osx-64
  - win-64

engine:
  - python=2.7
  - python=3.3
  - python=3.4
  - python=3.5

install:
  - conda config --add channels anaconda-notebook

script:
  - conda build --quiet conda.recipe

build_targets: conda
