package: anaconda-nb-extensions

platform:
  - linux-64
  - osx-64
  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

script:
  - conda build conda.recipe -c anaconda-nb-extensions -c anaconda-nb-extensions/label/dev 

build_targets: conda
