package:
  name: condaenvs
  version: "0.0.1dev"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python
  run:
    - python
    - nbwrapper

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-notebook
  license: TBD
