package:
  name: hello-world
  version: "0.1.0"

build:
  script: python setup.py install

requirements:
  build:
    - python
    - notebook

  run:
    - python
    - notebook
    - nbsetuptools
    - nbwrapper

test:
  requires:
    - mock
    - notebook
    - python
    - requests
    - nose

  commands:
    - nosetests -w ${SRC_DIR}

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-notebook
  license: TBD
