package:
  name: anaconda-nb-extensions
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - python
  run:
    - python
    - notebook >=4.2.0
    - nb_anacondacloud
    - nb_conda
    - nb_conda_kernels
    - nbpresent

about:
  summary: Make the Jupyter Notebook and Anaconda awesome together
  home: https://github.com/Anaconda-Platform/anaconda-nb-extensions
  license_file: LICENSE
  license: BSD License
