package:
  name: anaconda-notebook
  version: 3.0

requirements:
  run:
    - python
    - ipython
    - pyzmq
    - tornado
    - jinja2
    - jsonschema

app:
  entry: anaconda-notebook.bat                          [win]
  entry: anaconda-notebook                              [linux]
  entry: open ${PREFIX}/bin/anaconda_notebook.command   [osx]
  summary: Anaconda notebook (enhanced IPython)

about:
  home: http://ipython.org/notebook.html
  license: BSD
