package:
  name: anaconda-notebook
  version: "0.1.1"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
  run:
    - python
    # fine control of the notebook version
    - notebook ==4.0.6
    # our wrapper
    - nbwrapper
    # our standard extension set
    - nb_conda
    - nb_conda_kernels
    - nbpresent
    - nbbrowserpdf

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-notebook
  license: BSD
