package:
  name: anaconda-notebook
  version: "4.0.4"

requirements:
  build:
    - python
    - notebook ==4.0.4
  run:
    - python
    - notebook ==4.0.4
    - ipywidgets
    - ipyparallel
    - pandoc
    - jsonpointer

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-notebook
  license: TBD
