package:
  name: anaconda-notebook
  version: "4.0.6dev"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python
  run:
    - python
    # fine control of the notebook version
    - notebook ==4.0.6
    # our wrapper
    - nbwrapper
    # our nbserverextension
    - condaenvs
    - locker
    - nbpresent
    - nbbrowserpdf

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-notebook
  license: TBD
