package:
  name: anaconda-notebook
  version: "4.0.4"

requirements:
  build:
    - python
    - notebook ==4.0.4
  run:
    - python
    - notebook ==4.0.4
    - ipywidgets
    - ipyparallel
    - pandoc
    - jsonpointer

source:
  git_url: ../

about:
  home: https://github.com/ContinuumIO/wakari-app-ipython
  license: TBD
