package:
  name: anaconda-notebook
  version: "4.0.4"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python
    - notebook ==4.0.4
  run:
    - python
    - notebook ==4.0.4
    - ipywidgets
    - ipyparallel
    - pandoc
    - jsonpointer

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-notebook
  license: TBD
