package:
  name: anaconda-nb-extensions
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{% if environ.get('ANE_RELEASE', '0') == '1' %}{{ environ.get('ANE_BUILD_NUMBER', '0') }}{% else %}{{ environ.get('GIT_BUILD_STR', '0') }}{% endif %}

requirements:
  build:
    - python
  run:
    - python
    - ipyparallel
    - ipywidgets
    - pandoc
    # Our extensions
    - nb_anaconda_theme
    - nb_anacondacloud
    - nb_conda
    # nb_conda_kernels is a nb_conda dependency but it also provides the
    # machinery for kernel-environment on the fly generation
    - nb_conda_kernels
    # This two could be removed when notebook 4.2 is out because it will have
    # a native mechanism to read nbconfig from several places and a consistent
    # API to install the extensions in different places.
    - nb_config_manager
    - nbsetuptools

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-nb-extensions
  license: BSD
