package:
  name: anaconda-nb-extensions
  version: "0.1.2"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
  run:
    - python
    # fine control of the notebook version
    - notebook >= 4.1
    # our standard extension set
    - nb_anacondacloud
    - nb_conda
    - nb_conda_kernels
    - nb_config_manager
    - nbpresent
    - nbbrowserpdf

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/anaconda-nb-extensions
  license: BSD
